Description of join_struct
Home > replicate_regression > replicate_regression > utils > join_struct.m
join_struct
PURPOSE
c = join_struct(a,b)
SYNOPSIS
function c = join_struct(a,b)
DESCRIPTION
 c = join_struct(a,b)
 start with structure a and insert all fields from structure b
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
biotable_interpolation_graphics_std
replicate_regression_biotable [X_average, X_replicate, X_central, X_cross_average, X_cross_replicate, X_fit, options, statistics, options_update]
replicate_regression_complete [data_reg, options_complete, options_update] = replicate_regression_complete(data_replicates,options)
replicate_regression_core [x_central, x_replicate, sigma_central, sigma_replicate, parameters, x_average, sigma_average, x_sample] = replicate_regression_core(t,y,sigma,r,tt,options)
replicate_regression_core_single [x_central, x_replicate, sigma_central, sigma_replicate, parameters, x_average, sigma_average, x_sample] = replicate_regression_core_single(t,y,sigma,tt,options)
replicate_regression_display h = replicate_regression_display(t,y,sigma,l,t_true,x_true,result,options)
replicate_regression_load_data_table [data, data_replicates, data_pointwise_average, explanatory_variable] = replicate_regression_load_data_table(filename, foptions)
replicate_regression_set_options options = replicate_regression_set_options(t, y, sigma, fix_parameters, options_default, varargin)
replicate_regression_single_display replicate_regression_single_display(t,y,sigma,t_true,x_true,result,options)
replicate_regression_omics_analysis Script replicate_regression_omics_analysis
replicate_regression_omics_selected Script replicate_regression_omics_selected
biotable_combine_replicates [data_central, data_average, data_replicates, statistics, options, data_combined, data_collected] = biotable_combine_replicates(data, options)
SOURCE CODE
function c = join_struct(a,b)
% c = join_struct(a,b)
%
% start with structure a and insert all fields from structure b
c = a;
ff = fieldnames(b);
for it = 1:length(ff),
  c = setfield(c,ff{it},getfield(b,ff{it}));
end