Description of label_names
Home > replicate_regression > replicate_regression > utils > label_names.m
label_names
PURPOSE
function [label,indices] = label_names(names,allnames, method)
SYNOPSIS
function [label,indices] = label_names(names,allnames,method)
DESCRIPTION
 function [label,indices] = label_names(names,allnames, method)
 method 'multiple'
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
replicate_regression_load_data_table [data, data_replicates, data_pointwise_average, explanatory_variable] = replicate_regression_load_data_table(filename, foptions)
replicate_regression_omics_selected Script replicate_regression_omics_selected
Protein_name_to_bsu
UniProt_to_bsu
biotable_join_replicates [combined,collected] = biotable_join_replicates(data,p)
SOURCE CODE
% function [label,indices] = label_names(names,allnames, method)
% method 'multiple'
function [label,indices] = label_names(names,allnames,method)
case_sensitive=0;
if not(case_sensitive), names=upper(names); allnames=upper(allnames); end
if ~exist('method'), method = 'single'; end
switch method
 case 'multiple'
 label = cell(length(names),1);
 for k=1:length(names)
  hits = find(strcmp(allnames,names(k)));
  if length(hits)>0
    label{k} = hits;
  end
 end
case 'single'
 label = zeros(length(names),1);
 for k=1:length(names)
  hits = find(strcmp(allnames,names(k)));
  if length(hits)>0
    label(k) = hits(1);
  end
 end
case 'fields'
    allnames=strrep(allnames,'-','_');
    allnames=strrep(allnames,'/','_');
    allnames=strrep(allnames,'.','_');
    names=strrep(names,'-','_');
    names=strrep(names,'/','_');
    names=strrep(names,'.','_');
   indices=struct('a','');
   for i=1:length(allnames),
      allnames{i}
     eval(['indices.' allnames{i} '=' num2str(i) ';']);
  end
  label=zeros(length(names),1);
  for k=1:length(names)
     if isfield(indices,names{k}),
       label(k) = getfield(indices,names{k});
     end
  end
end