Description of load_any_table
Home > replicate_regression > replicate_regression > utils > load_any_table.m
load_any_table
PURPOSE
list = load_any_table(filename)
SYNOPSIS
function result = load_any_table(filename,delimiter)
DESCRIPTION
 list = load_any_table(filename)
 loads a tab-delimited file and puts it into a cell array
 filename: name of tab-delimited file containing strings and numbers
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
replicate_regression_load_data_table [data, data_replicates, data_pointwise_average, explanatory_variable] = replicate_regression_load_data_table(filename, foptions)
load_options_table tablefile can be th ename of the table file
sbtab_table_load sbtab = sbtab_table_load(filename)
SOURCE CODE
function result = load_any_table(filename,delimiter)
% list = load_any_table(filename)
%
% loads a tab-delimited file and puts it into a cell array
% filename: name of tab-delimited file containing strings and numbers
if ~exist('delimiter','var'), delimiter = sprintf('\t'); end
fid           = fopen(filename);
try
  column_titles = fgets(fid);
catch
  error(['File ' filename ' not found.']);
end
fclose(fid);
tab_pos = [0,unique([strfind(column_titles,delimiter)])];
textscanstring = repmat('%s',1,length(tab_pos));
fid = fopen(filename);
A   = textscan(fid,textscanstring,'delimiter',delimiter);
fclose(fid);
result = {};
for i =1:length(A),
  for k = 1:length(A{i}),
  result{k,i} = A{i}{k};
  end
end
result = result(:,find(sum(cellfun('length',result))>0));