Description of sbtab_table_load
Home > replicate_regression > replicate_regression > utils > sbtab_table_load.m
sbtab_table_load
PURPOSE
sbtab = sbtab_table_load(filename)
SYNOPSIS
function sbtab = sbtab_table_load(filename)
DESCRIPTION
 sbtab = sbtab_table_load(filename)
CROSS-REFERENCE INFORMATION
This function calls:
column transform a vector (row or column) into a column vector
load_any_table list = load_any_table(filename)
This function is called by:
replicate_regression_load_data_table [data, data_replicates, data_pointwise_average, explanatory_variable] = replicate_regression_load_data_table(filename, foptions)
SOURCE CODE
function sbtab = sbtab_table_load(filename)
% sbtab = sbtab_table_load(filename)
my_table = load_any_table(filename);
attribute_line = {};
if strcmp('!!',my_table{1,1}(1:2)),
 attribute_line = my_table(1,:);
 my_table       = my_table(2:end,:);
end
rows        = struct;
ind_data    = [];
if length(my_table),
while strcmp('!',my_table{2,1}(1)),
 row_header = my_table{2,1}(2:end);
 row_rest   = [{[]},my_table(2,2:end)];
 ind_data   = [ind_data, find(cellfun('length',row_rest))];
 my_table   = my_table([1,3:end],:);
 rows       = setfield(rows,row_header,row_rest);
end
ind_rows = setdiff(unique(ind_data),1);
column = struct;
column_names = {};
ind_column = [];
for it = 1:size(my_table,2),
  column_header = my_table{1,it};
  if strcmp('!',column_header(1)),
    column_header = column_header(2:end);
    column_names = [column_names; {column_header}];
    column_header = strrep(column_header,' ','_');
    column_header = strrep(column_header,':','_');
    column_header = strrep(column_header,'.','_');
    ind_column = [ind_column it];
    column = setfield(column,column_header,strtrim(my_table(2:end,it)));
  end
end
ind_data         = setdiff(ind_rows,ind_column);
data_headers     = my_table(1,ind_data);
data             = my_table(2:end,ind_data);
ind_uncontrolled = setdiff(1:size(my_table,2),[ind_column,ind_data]);
if length(ind_uncontrolled),
  uncontrolled_headers = my_table(1,ind_uncontrolled);
  uncontrolled         = my_table(2:end,ind_uncontrolled);
else
  uncontrolled_headers = [];
  uncontrolled         = '';
  ind_uncontrolled = [];
end
end
fn = fieldnames(rows);
data_attributes   = [];
column_attributes = [];
for it = 1:length(fn);
  data_attributes.(fn{it})   = rows.(fn{it})(ind_data);
  column_attributes.(fn{it}) = rows.(fn{it})(ind_column);
end
sbtab.filename          = filename;
sbtab.attributes        = attribute_line;
sbtab.rows              = rows;
sbtab.column.column_names = column_names;
sbtab.column.column     = column;
sbtab.column.attributes = column_attributes;
sbtab.column.ind        = ind_column;
sbtab.data.headers      = data_headers;
sbtab.data.attributes   = data_attributes;
sbtab.data.data         = strtrim(data);
sbtab.data.ind          = ind_data;
sbtab.uncontrolled.headers = uncontrolled_headers;
sbtab.uncontrolled.data = strtrim(uncontrolled);
sbtab.uncontrolled.ind  = ind_uncontrolled;