Description of maximise_bayesian_posterior_L1
Home > replicate_regression > replicate_regression > maximise_bayesian_posterior_L1.m
maximise_bayesian_posterior_L1
PURPOSE
function [x_max_posterior, neg_log_posterior, x_min, x_max, x_cov_posterior, y_cov_posterior] = maximise_bayesian_posterior_L1(data_mean, data_std, prior_mean, prior_std, R)
SYNOPSIS
function [x_max_posterior, neg_log_posterior, x_min, x_max, x_cov_posterior, y_cov_posterior] = maximise__bayesian_posterior_L1(data_mean, data_std, prior_mean, prior_std, R)
DESCRIPTION
function [x_max_posterior, neg_log_posterior, x_min, x_max, x_cov_posterior, y_cov_posterior] = maximise_bayesian_posterior_L1(data_mean, data_std, prior_mean, prior_std, R)
 Minimise -log posterior =   || (y(x)-ydata) / sigmay ||_L1
                           + || (x - xprior) / sigmax ||_L1
 where data vector y and parameter vector x are linearly related y(x) = R * x
 data_mean,  data_std : (n_data x 1) colunm vectors
 prior_mean, prior_std: (n_pars x 1) colunm vectors
 NOTE THAT THE SOLUTION NEED NOT BE UNIQUE!!
 Using linprog (the default) tends to give a symmetric solution; cplex may yield a non-symmetric solution
 NOTE that the posterior covariance matrices are not exact,  but
 computed via a simple heuristics:
 Start from the optimum point.
 Allow for an (additive) increase of the L1 norm by 1/2
 Determine, for each parameter, the minimum and maximum parameter value that can still
   be realised under this constraint
 Take 1/2 [xmax_i-xmin_i] as a "posterior standard deviation" and ignore correlations
 Turn these "standard deviations" into a covariance matrix, and derive from it the
 Covariance matrix of the data values y
CROSS-REFERENCE INFORMATION
This function calls:
maximise_bayesian_posterior_L1 function [x_max_posterior, neg_log_posterior, x_min, x_max, x_cov_posterior, y_cov_posterior] = maximise_bayesian_posterior_L1(data_mean, data_std, prior_mean, prior_std, R)
column transform a vector (row or column) into a column vector
This function is called by:
maximise_bayesian_posterior_L1 function [x_max_posterior, neg_log_posterior, x_min, x_max, x_cov_posterior, y_cov_posterior] = maximise_bayesian_posterior_L1(data_mean, data_std, prior_mean, prior_std, R)
replicate_regression_core [result, parameters, options, sample] = replicate_regression_core(t,y,sigma,r,tt,options)
replicate_regression_core_single [result, parameters, options, sample] = replicate_regression_core_single(t,y,sigma,tt,options)