function foptions = replicate_regression_omics_default_options()

% foptions = replicate_regression_omics_default_options()
%
% The default values for entries data_std_log, log_data_adjust_std_threshold, 
% log_data_adjust_std_factor refer to proteome data on log2 scale

foptions = struct(...
    'convenience_name', [], ...
    'translation_table_file', [replicate_regression_DIR '/resources/SubtiWiki_id_mapping_20090701_renamed.txt'], ...
    'set_std',[], ...
    'data_scale',[], ...
    'convert_to_logarithm',[],...
    'log_transformation','arithmetic',...
    'data_time_unit','min',...
    'data_min_data_points',3,...
    'basis',[],...
    'fixed_prior',0,...
    'prior_updating',5,...
    'updating_factor',1.2,...    
    'updating_factor_final',[],...    
    'update_prior_means',0,...
    'run_crossvalidation',1,...
    'postprocess_normalise',0,...
    'graphics_format','png',...
    'graphics_scale','linear',...
    'data_file_csv',[],...
    'result_file_matlab',[],...
    't_smooth',[],...
    'regression_t_interp',[],...
    'regression_tmin',[],...
    'regression_tmax',[],...
    'options_start_value',[],...
    'options_start_at_t',[],...
    'options_constant_before_start',[],...
    'options_out_csv',[],...
    'result_file_csv',[],...
    'graphics_file',[],...
    'log_file',[],...
    'graphics_individual',[],...
    'result_file_zip',[],...
    'normalise_by_median',1,...
    'ignore_std_deviations',1,...
    'data_min_num_replicates',1,...
    'data_std_log',0.17,...
    'abs_data_adjust_std_lower',0,...
    'abs_data_adjust_std_upper',inf,...
    'log_data_adjust_std_threshold',1.5,...
    'log_data_adjust_std_factor',0.7,...
    'data_std_minimal',10^-5,...
    'mark_outliers_percentage',0.02);
