Description of default
Home > replicate_regression > utils > default.m
default
PURPOSE
commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
SYNOPSIS
function commandstring = default(varargin)
DESCRIPTION
 commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
 usage eval(default('a','1','name','''Gonzo'''));
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
replicate_regression [result, options] = replicate_regression(t, y, sigma, r, varargin)
biotable_interpolation_graphics_std
replicate_regression_complete [data_reg, options_complete, options_update] = replicate_regression_complete(data_replicates,options)
replicate_regression_core [x_central, x_replicate, sigma_central, sigma_replicate, parameters, x_average, sigma_average, x_sample] = replicate_regression_core(t,y,sigma,r,tt,options)
replicate_regression_core_single [x_central, x_replicate, sigma_central, sigma_replicate, parameters, x_average, sigma_average, x_sample] = replicate_regression_core_single(t,y,sigma,tt,options)
replicate_regression_display h = replicate_regression_display(t,y,sigma,l,t_true,x_true,result,options)
replicate_regression_display_statistics replicate_regression_display_statistics(result, options, filename,image_format)
replicate_regression_load_data_table [data, data_replicates, data_pointwise_average, explanatory_variable] = replicate_regression_load_data_table(filename, foptions)
replicate_regression_save_data_table all = replicate_regression_save_data_table(data_table, rep_name, basename)
replicate_regression_single_display replicate_regression_single_display(t,y,sigma,t_true,x_true,result,options)
biotable_combine_replicates [data_central, data_average, data_replicates, statistics, options, data_combined, data_collected] = biotable_combine_replicates(data, options)
biotable_join_replicates [combined,collected] = biotable_join_replicates(data,p)
lognormal_log2normal convert mean and std dev of Gaussian random variable into
lognormal_normal2log convert characteristics of log-normal random variable X
plot_range h = plot_range(t,x_mean,x_inner,x_outer,col0,col1,col2,opacity,linestyle,linewidth)
table result = table(names,rownumbers,filename)
SOURCE CODE
function commandstring = default(varargin)
% commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
%
% usage eval(default('a','1','name','''Gonzo'''));
commandstring = '';
for it = 1:length(varargin)/2,
varname = varargin{it*2-1};
value_string = varargin{it*2};
commandstring = [commandstring, 'if ~exist(''',varname,''',''var''), ',varname,' = ',value_string,'; end; '];
end