Description of column
Home > replicate_regression > replicate_regression > utils > column.m
column
PURPOSE
transform a vector (row or column) into a column vector
SYNOPSIS
function x = column(x)
DESCRIPTION
 transform a vector (row or column) into a column vector
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
biotable_interpolation_graphics_std
maximise_bayesian_posterior_L1 function [x_max_posterior, neg_log_posterior, x_min, x_max, x_cov_posterior, y_cov_posterior] = maximise_bayesian_posterior_L1(data_mean, data_std, prior_mean, prior_std, R)
replicate_regression_core [result, parameters, options, sample] = replicate_regression_core(t,y,sigma,r,tt,options)
replicate_regression_core_single [result, parameters, options, sample] = replicate_regression_core_single(t,y,sigma,tt,options)
replicate_regression_set_options options = replicate_regression_set_options(t, y, sigma, fix_parameters, options_default, varargin)
biotable_join_replicates [combined,collected] = biotable_join_replicates(data,p)
sbtab_table_load SBTAB_TABLE_LOAD Load SBtab table from file, or generate it from a list of strings