Description of lognormal_log2normal
Home > replicate_regression > replicate_regression > utils > lognormal_log2normal.m
lognormal_log2normal
PURPOSE
convert mean and std dev of Gaussian random variable into
SYNOPSIS
function [mu,sigma] = lognormal_log2normal(mu_log,sigma_log,convention)
DESCRIPTION
 convert mean and std dev of Gaussian random variable into
 characteristics of random variable  Y = exp(X)
 convention 'arithmetic': mean and std dev of Y
 convention 'geometric': geometric mean and  spread = geom.mean * (geom.std.dev - 1 ) of Y
CROSS-REFERENCE INFORMATION
This function calls:
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
lognormal_log2normal convert mean and std dev of Gaussian random variable into
lognormal_normal2log convert characteristics of log-normal random variable X
This function is called by:
replicate_regression [result, options] = replicate_regression(t, y, sigma, r, flag_fix_parameters, varargin)
lognormal_log2normal convert mean and std dev of Gaussian random variable into