Description of replicate_regression_omics_default_options
Home > replicate_regression > replicate_regression_omics > replicate_regression_omics_default_options.m
replicate_regression_omics_default_options
PURPOSE
foptions = replicate_regression_omics_default_options()
SYNOPSIS
function foptions = replicate_regression_omics_default_options()
DESCRIPTION
 foptions = replicate_regression_omics_default_options()
 The default values for entries data_std_log, log_data_adjust_std_threshold,
 log_data_adjust_std_factor refer to proteome data on log2 scale
CROSS-REFERENCE INFORMATION
This function calls:
replicate_regression_DIR
This function is called by:
replicate_regression_omics_analysis -------------------------------------------------------------------
replicate_regression_omics_display Script replicate_regression_omics_selected