Description of replicate_regression_omics_display
Home > replicate_regression > replicate_regression_omics > replicate_regression_omics_display.m
replicate_regression_omics_display
PURPOSE
Script replicate_regression_omics_selected
SYNOPSIS
This is a script file.
DESCRIPTION
 Script replicate_regression_omics_selected
 Display results for a single protein; save graphics files.
 To run this script, a replicate regression for the entire omics data set must have been run before
 (see script replicate_regression_omics_analysis)
 Input variable: foptions_file
 Example:        foptions_file = [replicate_regression_PATH_NAME '/options_hahne_salt_stress_tagD.csv'];
CROSS-REFERENCE INFORMATION
This function calls:
biotable_interpolation_graphics_std
ca
join_struct c = join_struct(a,b)
label_names function [label,indices] = label_names(names,allnames, method)
load_options_table Options = load_options_table(tablefile)
replicate_regression_omics_default_options foptions = replicate_regression_omics_default_options()
This function is called by: