Description of rr_colors
Home > replicate_regression > replicate_regression > replicate_regression > rr_colors.m
rr_colors
PURPOSE
SYNOPSIS
function colors = rr_colors()
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demo_replicate_regression ----------------------------------------------------------------
biotable_interpolation_graphics_std
replicate_regression_display h = replicate_regression_display(t,y,sigma,l,t_true,x_true,result,options)
SOURCE CODE
function colors = rr_colors()
colors = {[0 0.3 1],[1 0.2 .2],[.9 .6 0],[0.3 1 0],[1 0.3 1]};